"use client";
import Link from "next/link";
import { Fragment, useState, type ReactNode } from "react";
import { CalendarDays, ChevronDown, ChevronRight, Goal, Handshake, MapPin, Menu, Shield, Trophy, Users } from "lucide-react";
import type { Row } from "@/lib/db";
import { ist } from "@/lib/domain";
import { LanguageSwitch, useLanguage } from "./provider";
import { MemberPredictions } from "./member-predictions";

const copy = {
  en: { overview:"Overview",matches:"Matches",table:"Points Table",players:"Players",prediction:"Prediction Leaderboard",login:"Member Login",public:"PUBLIC VIEW",title:"SUPER LEAGUE KERALA",sub:"Fixtures, results, standings and player statistics",next:"Next Match",latest:"Latest Result",noNext:"No upcoming fixture has been published.",fullTime:"Full Time",top:"Top Scorers",assists:"Assists",contrib:"Goal Contributions",played:"P",regWins:"W",shootWins:"PW",shootLosses:"PL",regLosses:"L",gf:"GF",ga:"GA",gd:"GD",pts:"Pts",rank:"Rank",member:"Member",predicted:"Matches Predicted",total:"Total Points",updated:"Updated",matchCentre:"Match Centre",match:"Match",events:"Goal events",shootoutKicks:"Penalty shootout",scored:"Scored",missed:"Missed",recentForm:"Last 10 performances",noForm:"No completed matches yet.",noStats:"Player statistics will appear after goal events are entered.",noResults:"No finalized results yet.",home:"Home",pointsRule:"SLK table: 3 points for a 90-minute win · 2 for a shootout win · 1 for a shootout loss · 0 for a 90-minute loss.",tiebreakRule:"Tiebreakers: points, head-to-head points, head-to-head goal difference, overall goal difference, goals scored, then Fair Play rank.",predictionRule:"SBK predictions continue to use only the score and result after 90 minutes plus stoppage time. Shootouts never affect prediction points.",shootoutWon:"Won on penalties",shieldWinner:"Super League Shield Winner",semiFinalist:"Semi-finalist (Positions 1–4)",viewFull:"View full leaderboard",collapse:"Show Top 10",predictScore:"Predict your score" },
  ml: { overview:"അവലോകനം",matches:"മത്സരങ്ങൾ",table:"പോയിന്റ് പട്ടിക",players:"കളിക്കാർ",prediction:"പ്രവചന ലീഡർബോർഡ്",login:"മെമ്പർ ലോഗിൻ",public:"പബ്ലിക് വ്യൂ",title:"സൂപ്പർ ലീഗ് കേരള",sub:"മത്സരങ്ങൾ, ഫലങ്ങൾ, പോയിന്റ് പട്ടിക, കളിക്കാരുടെ കണക്കുകൾ",next:"അടുത്ത മത്സരം",latest:"അവസാന ഫലം",noNext:"വരാനിരിക്കുന്ന മത്സരം പ്രസിദ്ധീകരിച്ചിട്ടില്ല.",fullTime:"ഫുൾ ടൈം",top:"ടോപ് സ്കോറേഴ്സ്",assists:"അസിസ്റ്റുകൾ",contrib:"ഗോൾ കോൺട്രിബ്യൂഷൻസ്",played:"മ",regWins:"W",shootWins:"PW",shootLosses:"PL",regLosses:"L",gf:"GF",ga:"GA",gd:"GD",pts:"പോ",rank:"റാങ്ക്",member:"അംഗം",predicted:"പ്രവചിച്ച മത്സരങ്ങൾ",total:"ആകെ പോയിന്റ്",updated:"പുതുക്കിയത്",matchCentre:"മാച്ച് സെന്റർ",match:"മത്സരം",events:"ഗോൾ വിവരങ്ങൾ",shootoutKicks:"പെനാൽറ്റി ഷൂട്ടൗട്ട്",scored:"ഗോൾ ആയി",missed:"ഗോൾ ആയില്ല",recentForm:"അവസാന 10 മത്സരങ്ങളിലെ പ്രകടനം",noForm:"പൂർത്തിയായ മത്സരങ്ങളില്ല.",noStats:"ഗോൾ വിവരങ്ങൾ ചേർത്ത ശേഷം കളിക്കാരുടെ കണക്കുകൾ ഇവിടെ വരും.",noResults:"ഫലം സ്ഥിരീകരിച്ച മത്സരങ്ങളില്ല.",home:"ഹോം",pointsRule:"SLK പട്ടിക: 90 മിനിറ്റ് ജയം 3 · ഷൂട്ടൗട്ട് ജയം 2 · ഷൂട്ടൗട്ട് തോൽവി 1 · 90 മിനിറ്റ് തോൽവി 0 പോയിന്റ്.",tiebreakRule:"ടൈബ്രേക്കർ: പോയിന്റ്, ഹെഡ്-ടു-ഹെഡ് പോയിന്റ്, ഹെഡ്-ടു-ഹെഡ് ഗോൾ വ്യത്യാസം, ആകെ ഗോൾ വ്യത്യാസം, നേടിയ ഗോളുകൾ, ഫെയർ പ്ലേ റാങ്ക്.",predictionRule:"SBK പ്രവചനത്തിന് 90 മിനിറ്റും സ്റ്റോപ്പേജ് സമയവും കഴിഞ്ഞുള്ള സ്കോറും ഫലവും മാത്രം. ഷൂട്ടൗട്ട് പ്രവചന പോയിന്റിനെ ബാധിക്കില്ല.",shootoutWon:"പെനാൽറ്റിയിൽ വിജയിച്ചത്",shieldWinner:"സൂപ്പർ ലീഗ് ഷീൽഡ് ജേതാവ്",semiFinalist:"സെമി ഫൈനലിസ്റ്റ് (1–4 സ്ഥാനങ്ങൾ)",viewFull:"മുഴുവൻ ലീഡർബോർഡ് കാണുക",collapse:"Top 10 മാത്രം കാണിക്കുക",predictScore:"നിങ്ങളുടെ സ്കോർ പ്രവചിക്കുക" }
} as const;
const leaderboardCopy = {
  en: { serial:"S.No.",winner:"Who will win the match?",score:"What will the score be?",first:"Who will score first?",round:"Round" },
  ml: { serial:"ക്രമ നമ്പർ",winner:"മത്സരത്തിൽ ആര് ജയിക്കും?",score:"സ്കോർ എന്തായിരിക്കും?",first:"ആരാണ് ആദ്യം ഗോൾ നേടുക?",round:"റൗണ്ട്" },
} as const;
const name = (row: Row, key: string, lang: "en"|"ml") => row[`${key}_${lang}`] || row[`${key}_en`] || "—";
function Badge({src,label}:{src?:string;label:string}) { return src ? <img className="slk-team-badge" src={src} alt={label} /> : <span className="slk-team-placeholder" role="img" aria-label={label}><Shield /></span>; }


export function PublicHeader() {
  const {lang} = useLanguage(), t=copy[lang];
  const [menu,setMenu]=useState(false);
  return (
    <header className="slk-public-header">
      <Link href="/SuperLeagueKerala" className="slk-public-brand"><img src="/sbk-logo.png" alt="SBK"/><span>SBK <b>Football Hub</b></span></Link>
      <button className="slk-menu-button" aria-label="Menu" onClick={()=>setMenu(!menu)}><Menu/></button>
      <nav className={menu?"open":""}>
        <Link href="/SuperLeagueKerala#overview">{t.overview}</Link>
        <Link href="/SuperLeagueKerala#matches">{t.matches}</Link>
        <Link href="/SuperLeagueKerala#table">{t.table}</Link>
        <Link href="/SuperLeagueKerala#players">{t.players}</Link>
        <Link href="/SuperLeagueKerala#predictions">{t.prediction}</Link>
        <Link href="/news" className="slk-news-link">{lang === "ml" ? "വാർത്തകൾ" : "News Portal"}</Link>
      </nav>
      <LanguageSwitch />
      <Link className="slk-login" href="/">{t.login}</Link>
    </header>
  );
}

export function PublicSportsHub({data}:{data:Row}) {
    const {lang} = useLanguage(), t=copy[lang], [menu,setMenu]=useState(false);
    const upcoming=[...data.fixtures].filter((f:Row)=>f.status==="scheduled"&&new Date(f.kickoff)>new Date()).sort((a:Row,b:Row)=>+new Date(a.kickoff)-+new Date(b.kickoff))[0];
    const finals=[...data.fixtures].filter((f:Row)=>f.status==="finalized").sort((a:Row,b:Row)=>+new Date(b.kickoff)-+new Date(a.kickoff));
    const latest=finals[0];
    const playerRows=(metric:"top"|"assists"|"contrib")=>{const key=metric==="top"?"goals":metric==="assists"?"assists":"contributions";return [...data.players].filter((player:Row)=>Number(player[key])>0).sort((a:Row,b:Row)=>Number(b[key])-Number(a[key])).slice(0,5);};
    return <div className="slk-public">
      <PublicHeader />
      <main>
      <section className="slk-hero" id="overview"><div><span className="slk-public-pill">{t.public}</span><h1>{t.title}</h1><p>{t.sub}</p></div><img src="/slk-logo-white.webp" alt="Super League Kerala"/></section>
      <section className="slk-match-grid" id="matches">
        <MatchFeature title={t.next} fixture={upcoming} empty={t.noNext} lang={lang} action={t.matchCentre}/>
        <MatchFeature title={t.latest} fixture={latest} empty={t.noResults} lang={lang} result action={t.fullTime}/>
      </section>
      <section className="slk-data-section" id="table">
        <article className="slk-data-card slk-table-card"><CardTitle icon={<Trophy/>} title={t.table}/><div className="slk-points-note"><strong>{t.pointsRule}</strong><span>{t.tiebreakRule}</span><span>{t.predictionRule}</span></div><div className="slk-table-legend" aria-label="Standings highlights"><span><i className="shield"/>{t.shieldWinner}</span><span><i className="semifinal"/>{t.semiFinalist}</span></div><Standings rows={data.table} fixtures={data.fixtures} t={t} lang={lang}/></article>
        <div className="slk-stat-cards" id="players">
          <article className="slk-data-card slk-stat-card"><CardTitle icon={<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polygon points="12 6 16.5 9 14.5 14 9.5 14 7.5 9"/><line x1="12" y1="6" x2="12" y2="2"/><line x1="16.5" y1="9" x2="21.5" y2="8"/><line x1="14.5" y1="14" x2="18" y2="19"/><line x1="9.5" y1="14" x2="6" y2="19"/><line x1="7.5" y1="9" x2="2.5" y2="8"/></svg>} title={t.top}/><PlayerStats rows={playerRows("top")} metric="top" t={t} lang={lang}/></article>
          <article className="slk-data-card slk-stat-card"><CardTitle icon={<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 15v3a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-3c0-1.5-1-3-2.5-3.5L15 10l-2-3-6 3c-1.5.5-2.5 2-2.5 3.5V15z"/><line x1="7" y1="18" x2="7" y2="21"/><line x1="11" y1="18" x2="11" y2="21"/><line x1="15" y1="18" x2="15" y2="21"/><line x1="13" y1="10" x2="16" y2="14"/></svg>} title={t.assists}/><PlayerStats rows={playerRows("assists")} metric="assists" t={t} lang={lang}/></article>
          <article className="slk-data-card slk-stat-card"><CardTitle icon={<Users/>} title={t.contrib}/><PlayerStats rows={playerRows("contrib")} metric="contrib" t={t} lang={lang}/></article>
        </div>
      </section>
      <section className="slk-results-section"><div className="slk-section-title"><div><small>{t.matchCentre}</small><h2>{t.matches}</h2></div></div><div className="slk-results-grid">{finals.slice(0,6).map((f:Row)=><ResultCard key={f.id} fixture={f} events={data.events.filter((e:Row)=>e.fixture_id===f.id)} kicks={data.shootoutKicks.filter((k:Row)=>k.fixture_id===f.id)} lang={lang} t={t}/>)}</div></section>
      <section className="slk-prediction-public" id="predictions"><div className="slk-section-title"><div><small>SBK COMMUNITY</small><h2>{t.prediction}</h2></div><div className="slk-prediction-actions"><span>{t.updated}: {ist(data.generatedAt,lang)}</span><Link href="/" className="slk-predict-cta">{t.predictScore}<ChevronRight/></Link></div></div><PredictionLeaderboard rows={data.predictions} rounds={data.rounds} memberPredictions={data.memberPredictions} t={t} lang={lang}/></section>
    </main>
    <footer className="slk-public-footer"><img src="/sbk-logo.png" alt="SBK"/><p>Soccer Blues of Keralam · Fans predict. Football unites.</p><Link href="/">{t.login}<ChevronRight/></Link></footer>
  </div>;
}
function CardTitle({icon,title}:{icon:ReactNode;title:string}) { return <div className="slk-data-card-title"><span>{icon}</span><h2>{title}</h2></div>; }
function MatchFeature({title,fixture,empty,lang,result,action}:{title:string;fixture?:Row;empty:string;lang:"en"|"ml";result?:boolean;action:string}) { const t=copy[lang]; return <article className={`slk-match-feature ${result?"result":"upcoming"}`}><div className="slk-card-head"><strong>{title}</strong><span className={result?"result":"upcoming"}>{result?"FULL TIME":"UPCOMING"}</span></div>{fixture?<><strong className="match-number-label">{t.match} {fixture.match_number}</strong><div className="slk-versus"><div><Badge src={fixture.home_badge} label={name(fixture,"home",lang)}/><b>{name(fixture,"home",lang)}</b></div><strong>{result?`${fixture.home_goals} – ${fixture.away_goals}`:"VS"}</strong><div><Badge src={fixture.away_badge} label={name(fixture,"away",lang)}/><b>{name(fixture,"away",lang)}</b></div></div><div className="slk-match-footer"><div className="slk-match-meta"><span><CalendarDays/>{ist(fixture.kickoff,lang)}</span>{name(fixture,"venue",lang)!=="—"&&<span><MapPin/>{name(fixture,"venue",lang)}</span>}</div>{!result&&<Link href="/" className="slk-predict-cta">{t.predictScore}<ChevronRight/></Link>}</div></>:<p className="slk-empty">{empty}</p>}</article>; }
  function Standings({rows,fixtures,t,lang}:{rows:Row[];fixtures:Row[];t:any;lang:"en"|"ml"}) { const [expanded,setExpanded]=useState<string|null>(null); const form=(teamId:string)=>fixtures.filter(f=>f.status==="finalized"&&(f.home_id===teamId||f.away_id===teamId)).sort((a,b)=>+new Date(b.kickoff)-+new Date(a.kickoff)).slice(0,10).map(f=>{const home=f.home_id===teamId,forGoals=Number(home?f.home_goals:f.away_goals),against=Number(home?f.away_goals:f.home_goals),code=forGoals>against?"W":forGoals<against?"L":f.shootout_winner===(home?"home":"away")?"PW":"PL";const opponent=home?name(f,"away",lang):name(f,"home",lang);return {id:String(f.id),home_goals:f.home_goals,away_goals:f.away_goals,code,opponent};}); return <div className="slk-public-table"><table><thead><tr><th>Pos</th><th>Club</th><th>{t.played}</th><th title="90-minute wins">{t.regWins}</th><th title="Penalty shootout wins">{t.shootWins}</th><th title="Penalty shootout losses">{t.shootLosses}</th><th title="90-minute losses">{t.regLosses}</th><th>{t.gf}</th><th>{t.ga}</th><th>{t.gd}</th><th>{t.pts}</th></tr></thead><tbody>{rows.map(r=>{const position=Number(r.table_position),prev=r.previous_position?Number(r.previous_position):position,movement=prev-position,open=expanded===r.team_id,recent=form(r.team_id);return <Fragment key={r.team_id}><tr className={`${position===1?"slk-shield-row":position<=4?"slk-semifinal-row":""} slk-team-row`} tabIndex={0} aria-expanded={open} onClick={()=>setExpanded(open?null:r.team_id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setExpanded(open?null:r.team_id);}}}><td><div className="slk-pos-wrap"><b>{r.table_position}</b>{movement>0?<span className="pos-up">↑ {movement}</span>:movement<0?<span className="pos-down">↓ {-movement}</span>:<span className="pos-same">-</span>}</div></td><td><span className="slk-club"><Badge src={r.badge} label={name(r,"name",lang)}/><strong>{name(r,"name",lang)}</strong><ChevronDown className={open?"open":""}/></span></td><td>{r.played}</td><td>{r.regulation_wins}</td><td>{r.shootout_wins}</td><td>{r.shootout_losses}</td><td>{r.regulation_losses}</td><td>{r.goals_for}</td><td>{r.goals_against}</td><td>{r.goal_difference}</td><td><b>{r.points}</b></td></tr>{open&&<tr className="slk-team-form-row"><td colSpan={11}><strong>{t.recentForm}</strong>{recent.length?<div className="slk-form-strip">{recent.map(match=><span key={match.id} className={`form-${match.code.toLowerCase()}`} title={`${match.opponent} · ${match.home_goals}–${match.away_goals}`}>{match.code}</span>)}</div>:<small>{t.noForm}</small>}</td></tr>}</Fragment>})}</tbody></table></div>; }
  function PredictionLeaderboard({rows,rounds,memberPredictions,t,lang}:{rows:Row[];rounds:Row[];memberPredictions:Row[];t:any;lang:"en"|"ml"}) { const labels=leaderboardCopy[lang],[expanded,setExpanded]=useState<string|null>(null),[showAll,setShowAll]=useState(false),visibleRows=showAll?rows:rows.slice(0,10); return <div className="slk-public-table slk-prediction-table"><table><thead><tr><th rowSpan={2}>{labels.serial}</th><th rowSpan={2}>{t.rank}</th><th rowSpan={2}>{t.member}</th><th rowSpan={2}>{labels.winner}</th><th rowSpan={2}>{labels.score}</th><th rowSpan={2}>{labels.first}</th><th rowSpan={2}>{t.predicted}</th>{rounds.length>0&&<th colSpan={rounds.length} className="round-group">{labels.round}</th>}<th rowSpan={2}>{t.total}</th></tr>{rounds.length>0&&<tr>{rounds.map(round=><th key={round.id} title={name(round,"name",lang)}>{round.sort_order}</th>)}</tr>}</thead><tbody>{visibleRows.map((r:Row,index:number)=>{const position=Number(r.rank),prev=r.previous_rank?Number(r.previous_rank):position,movement=prev-position;return <Fragment key={r.public_key}><tr><td>{index+1}</td><td><div className="slk-pos-wrap"><span className={`slk-rank-badge rank-${r.rank}`}>{r.rank}</span>{movement>0?<span className="pos-up">↑ {movement}</span>:movement<0?<span className="pos-down">↓ {-movement}</span>:<span className="pos-same">-</span>}</div></td><td><button className="member-prediction-toggle" aria-expanded={expanded===r.public_key} aria-controls={`public-predictions-${r.public_key}`} onClick={()=>setExpanded(expanded===r.public_key?null:r.public_key)}><strong>{r.display_name}</strong><ChevronDown size={14}/></button></td><td>{r.correct}</td><td>{r.exact}</td><td>{r.first_goal_correct}</td><td>{r.participation}</td>{rounds.map(round=><td key={round.id} className="round-score">{r.round_points?.[round.id]??0}</td>)}<td><strong>{r.points}</strong></td></tr>{expanded===r.public_key&&<tr className="member-prediction-row" id={`public-predictions-${r.public_key}`}><td colSpan={8+rounds.length}><div className="member-prediction-heading"><strong>{r.display_name}</strong><button className="text-button" onClick={()=>setExpanded(null)}>{lang==="ml"?"പ്രവചനങ്ങൾ മറയ്ക്കുക":"Hide predictions"}</button></div><MemberPredictions rows={memberPredictions.filter((item:Row)=>item.public_key===r.public_key)}/></td></tr>}</Fragment>})}</tbody></table>{rows.length>10&&<div className="slk-leaderboard-more"><button onClick={()=>{setShowAll(!showAll);setExpanded(null);}}>{showAll?t.collapse:t.viewFull}<ChevronDown className={showAll?"open":""}/></button></div>}</div>; }
function PlayerStats({rows,metric,t,lang}:{rows:Row[];metric:string;t:any;lang:"en"|"ml"}) { const key=metric==="top"?"goals":metric==="assists"?"assists":"contributions"; return rows.length?<div className="slk-player-grid">{rows.slice(0,12).map((r,i)=><article key={r.player_id}><span className="slk-player-rank">{i+1}</span><Badge src={r.badge} label={name(r,"team",lang)}/><div><strong>{name(r,"player",lang)}</strong><small>{name(r,"team",lang)}{r.shirt_number?` · #${r.shirt_number}`:""}</small></div><b>{r[key]}</b></article>)}</div>:<p className="slk-empty">{t.noStats}</p>; }
function ResultCard({fixture,events,kicks,lang,t}:{fixture:Row;events:Row[];kicks:Row[];lang:"en"|"ml";t:any}) { const shootoutTeam=fixture.shootout_winner?name(fixture,fixture.shootout_winner,lang):null; return <article className="slk-result-card"><small><b className="match-number-label">{t.match} {fixture.match_number}</b> · {name(fixture,"round",lang)} · {ist(fixture.kickoff,lang)}</small><div className="slk-result-score"><Badge src={fixture.home_badge} label={name(fixture,"home",lang)}/><strong>{fixture.home_goals} – {fixture.away_goals}</strong><Badge src={fixture.away_badge} label={name(fixture,"away",lang)}/></div>{shootoutTeam&&<p className="slk-shootout-result">{t.shootoutWon}: <b>{shootoutTeam}</b></p>}{events.length>0&&<details><summary>{t.events}</summary>{events.map(e=><p key={e.id}><b>{e.minute}{e.added_time?`+${e.added_time}`:""}′</b> {name(e,"scorer",lang)}{e.assist_en?` · ${name(e,"assist",lang)}`:""}</p>)}</details>}{kicks.length>0&&<details><summary>{t.shootoutKicks}</summary>{kicks.map(k=><p key={k.id} className={k.scored?"shootout-scored":"shootout-missed"}><b>{k.scored?"✓":"×"}</b> {name(k,"player",lang)} · {k.scored?t.scored:t.missed}</p>)}</details>}</article>; }
